server:
  port: 9129

spring:
  application:
    name: afconfig-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:config
    username: root
    password: 123456
  sql:
    init:
      schema-locations: classpath:/db.sql
      mode:  always
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
